---
fullname: Matrix Canonical Forms
shortname: matrix_canonical_forms
opam_name: coq-matrix-canonical-forms
organization: coq-community
community: true
action: true
branch: main

synopsis: Various kinds of normal forms for matrices in Coq using Mathematical Components

description: |-
  This library builds on Mathematical Components and CoqEAL to provide formal
  proofs in Coq about matrices: the existence of Smith normal forms, Jordan
  normal forms, etc., converging towards a proof of the Perron-Frobenius theorem.

publications:
- pub_url: https://tel.archives-ouvertes.fr/tel-00986283/
  pub_title: Interaction entre algèbre linéaire et analyse en formalisation des mathématiques

authors:
- name: Guillaume Cano
  initial: true

maintainers:
- name: Yves Bertot
  nickname: ybertot

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.15~") | (= "dev")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.12.0" & < "1.13~") | (= "dev")}'
  description: |-
    [MathComp ssreflect](https://math-comp.github.io) 1.12 or later
- opam:
    name: coq-mathcomp-fingroup
  description: |-
    [MathComp fingroup](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp algebra](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-real-closed
    version: '{(>= "1.1.2" & < "1.2~") | (= "dev")}'
  description: |-
    [MathComp real-closed](https://math-comp.github.io) 1.1.2 or later
- opam:
    name: coq-coqeal
    version: '{(>= "1.0.5" & < "1.1~") | (= "dev")}'
  description: |-
    [CoqEAL](https://github.com/coq-community/coqeal) 1.0.5 or later


tested_coq_opam_versions:
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.10'
  repo: 'mathcomp/mathcomp'

tested_coq_nix_versions:
- coq_version: 'master'
  extra_dev_dependencies:
  - nix_name: mathcomp

namespace: matrix_canonical_forms

keywords:
- name: matrix
- name: matrices
- name: normal form

categories:
- name: Mathematics/Algebra

build: |-
  ## Building and installation instructions

  To build and install, do:

  ``` shell
  git clone https://github.com/coq-community/matrix_canonical_forms.git
  cd matrix_canonical_forms
  make   # or make -j <number-of-cores-on-your-machine>
  make install
  ```

documentation: |-
  ## Documentation

  For more information about the project, see the
  [website](https://www-sop.inria.fr/marelle/Guillaume.Cano/).
---
